version: "3.7"

services:
  web:
    image: 'isspay:api'
    command: "ruby setup.rb"
    networks:
      - "isspay-net"
    environment:
      DB_HOST: "${DB_HOST}"
      RAILS_ENV: 'production'
      API_URL: "${API_URL}"
    depends_on:
      - db
    volumes:
      - /tmp/sockets:/app/tmp/sockets
  db:
    container_name: "${DB_HOST}"
    image: 'postgres:alpine'
    networks:
      - 'isspay-net'
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWD}"
    volumes:
      - "${VOLUME}:/var/lib/postgresql/data"
  web_server:
    image: 'nginx:alpine'
    ports:
      - "80:80"
    networks:
      - "isspay-net"
    volumes:
      - "${NGINX_CONFIG}:/etc/nginx/conf.d"
      - /tmp/sockets:/app/tmp/sockets
    depends_on:
      - web
networks:
  isspay-net:
volumes:
  my-bundle: