default: &default
  REDIS_URL: 'redis://127.0.0.1:6379/1'

development:
  <<: *default
  API_URL: 'https://40c079eb.ngrok.io'

test:
  <<: *default
  API_URL: 'https://localhost'

production:
  REDIS_URL: 'redis://127.0.0.1:6379/1'
  API_URL: 'https://40c079eb.ngrok.io'